//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApprovalMaster
    {
        public int ApprovalID { get; set; }
        public string WorkflowType { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public int Approver1ID { get; set; }
        public string Approver1Comments { get; set; }
        public string Approver1Status { get; set; }
        public Nullable<int> Approver2ID { get; set; }
        public string Approver2Comments { get; set; }
        public string Approver2Status { get; set; }
        public Nullable<int> Approver3ID { get; set; }
        public string Approver3Comments { get; set; }
        public string Approver3Status { get; set; }
        public Nullable<int> Approver4ID { get; set; }
        public string Approver4Comments { get; set; }
        public string Approver4Status { get; set; }
        public Nullable<int> Approver5ID { get; set; }
        public string Approver5Comments { get; set; }
        public string Approver5Status { get; set; }
        public Nullable<int> Approver6ID { get; set; }
        public string Approver6Comments { get; set; }
        public string Approver6Status { get; set; }
        public Nullable<int> Approver7ID { get; set; }
        public string Approver7Comments { get; set; }
        public string Approver7Status { get; set; }
        public Nullable<int> Approver8ID { get; set; }
        public string Approver8Comments { get; set; }
        public string Approver8Status { get; set; }
        public Nullable<int> Approver9ID { get; set; }
        public string Approver9Comments { get; set; }
        public string Approver9Status { get; set; }
        public Nullable<int> Approver10ID { get; set; }
        public string Approver10Comments { get; set; }
        public string Approver10Status { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
