//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendorMaster
    {
        public int VendorVendorID { get; set; }
        public string VendorCorporateIdentificationNumber { get; set; }
        public string VendorVendorName { get; set; }
        public string VendorTypeofEntity { get; set; }
        public string VendorAuthorisedSignatory { get; set; }
        public string VendorRegisteredAddress { get; set; }
        public string VendorBranchOffice1 { get; set; }
        public string VendorBranchOffice2 { get; set; }
        public string VendorBranchOffice3 { get; set; }
        public string VendorBranchOffice4 { get; set; }
        public string VendorBranchOffice5 { get; set; }
        public string CorporateAddress { get; set; }
        public string NameoftheProprietor { get; set; }
        public string PAN { get; set; }
        public string AdhaarCardNo { get; set; }
        public string LLPIN { get; set; }
        public string Partner1Name { get; set; }
        public Nullable<int> Partner1Age { get; set; }
        public string Partner1FatherName { get; set; }
        public string Partner1Address { get; set; }
        public string Partner2Name { get; set; }
        public Nullable<int> Partner2Age { get; set; }
        public string Partner2FatherName { get; set; }
        public string Partner2Address { get; set; }
        public string Partner3Name { get; set; }
        public Nullable<int> Partner3Age { get; set; }
        public string Partner3FatherName { get; set; }
        public string Partner3Address { get; set; }
        public string Partner4Name { get; set; }
        public Nullable<int> Partner4Age { get; set; }
        public string Partner4FatherName { get; set; }
        public string Partner4Address { get; set; }
        public string Partner5Name { get; set; }
        public Nullable<int> Partner5Age { get; set; }
        public string Partner5FatherName { get; set; }
        public string Partner5Address { get; set; }
        public string Partner6Name { get; set; }
        public Nullable<int> Partner6Age { get; set; }
        public string Partner6FatherName { get; set; }
        public string Partner6Address { get; set; }
        public string Partner7Name { get; set; }
        public Nullable<int> Partner7Age { get; set; }
        public string Partner7FatherName { get; set; }
        public string Partner7Address { get; set; }
        public string Partner8Name { get; set; }
        public Nullable<int> Partner8Age { get; set; }
        public string Partner8FatherName { get; set; }
        public string Partner8Address { get; set; }
        public string Partner9Name { get; set; }
        public Nullable<int> Partner9Age { get; set; }
        public string Partner9FatherName { get; set; }
        public string Partner9Address { get; set; }
        public string Partner10Name { get; set; }
        public Nullable<int> Partner10Age { get; set; }
        public string Partner10FatherName { get; set; }
        public string Partner10Address { get; set; }
    }
}
