//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendorTemplate
    {
        public int ID { get; set; }
        public string VendorCompany { get; set; }
        public string VendorPartnershipFirm { get; set; }
        public string VendorSoleProprietorship { get; set; }
        public string VendorLLPF { get; set; }
        public string VendorOthers { get; set; }
    }
}
